<?php
/**
 * Plugin Name: BW List Builder
 * Plugin URI: http://blargmedia.ca
 * Description: Email List builder example project from Udemy Ultimate WP Plugin course
 * Version: 0.0.1
 * Author: Ben Wong // blargmedia.ca
 * Author URI: http://blargmedia.ca
 */

/* 0. table of contents */
/*
    1. hooks
      1.1   custom shortcodes
      1.2   custom admin column headers - subscribers
      1.3   custom admin column data - subscribers
      1.4   titles for post types without titles
      1.5   custom admin column headers - lists
      1.6   custom admin column data - lists
      1.7   ajax actions for non logged in users
      1.8   ajax actions for logged in users with privs

    2. shortcodes
      2.1   bwlb_register_shortcodes()
      2.2   bwlb_form_shortcode()

    3. filters
      3.1   bwlb_subscriber_column_headers()
      3.2   bwlb_subscriber_column_data()
      3.2.1 bwlb_register_custom_admin_titles()
      3.2.2 bwlb_custom_admin_titles()
      3.3   bwlb_list_column_headers
      3.4   bwlb_list_column_data


    4. external scripts

    5. actions
      5.1   bwlb_save_subscription()
      5.2   bwlb_save_subscriber()
      5.3   bwlb_add_subscription()

    6. helpers
      6.1   bwlb_subscriber_has_subscription()
      6.2   bwlb_get_subscriptions()
      6.3   bwlb_get_subscriptions()
      6.4   bwlb_return_json()
      6.5   bwlb_get_acf_key()
      6.6   bwlb_get_subscriber_data()
      6.7   bwlb_validate_subscriber()

    7. custom post types
    8. admin pages
    9. settings

*/


/* 1. hooks */

// 1.1
// register custom shortcodes on init action hook
add_action('init', 'bwlb_register_shortcodes');

// 1.2
// register custom admin column headers
add_filter('manage_edit-bwlb_subscriber_columns', 'bwlb_subscriber_column_headers');

// 1.3
// register custom admin column data with priority 1 and indicate we need 2 params
add_filter('manage_bwlb_subscriber_posts_custom_column', 'bwlb_subscriber_column_data', 1, 2);

// 1.4
// register custom titles for post type data without titles
add_action('admin_head-edit.php', 'bwlb_register_custom_admin_titles');

// 1.5
// register custom admin column headers
add_filter('manage_edit-bwlb_list_columns', 'bwlb_list_column_headers');

// 1.6
// register custom admin column data with priority 1 and indicate we need 2 params
add_filter('manage_bwlb_list_posts_custom_column', 'bwlb_list_column_data', 1, 2);

// 1.7
// register ajax actions for regular website (not logged in) visitors
add_action('wp_ajax_nopriv_bwlb_save_subscription', 'bwlb_save_subscription');

// 1.8
// register ajax actions for logged-in users with privs
add_action('wp_ajax_bwlb_save_subscription','bwlb_save_subscription');


/* 2. shortcodes */

// 2.1
// registers all custom shortcodes - can add more here later
function bwlb_register_shortcodes() {

  // sets bwlb_form against form_shortcode callback function
  add_shortcode('bwlb_form', 'bwlb_form_shortcode');

}

// 2.2
// create the html output to be generated by the shortcode
function bwlb_form_shortcode( $args, $content="" ) {  // wp auto passes in the args and contents

  // get the list id from the args with sanity checking
  $list_id = 0;
  if ( isset(args['id']) ) $list_id = (int) $args['id'];




  // setup output variable - the form html that will be returned
  $output = '
    <div class="bwlb">
      <form id="bwlb_form" name="bwlb_form" class="bwlb-form" method="post"
      action="/wp_wecf/wp-admin/admin-ajax.php?action=bwlb_save_subscription">

        <input type="hidden" name="bwlb_list" value="'. $list_id .'">

        <p class="bwlb-input-container">
          <label>Your Name</label><br/>
          <input type="text" name="bwlb_fname" placeholder="first name" />
          <input type="text" name="bwlb_lname" placeholder="last name" />
        </p>
        <p class="bwlb-input-container">
          <label>Your Email</label><br/>
          <input type="email" name="bwlb_email" placeholder="email" />
        </p>';

        // validate any incoming content and include in the output if needed
        if ( strlen($content) ):
          $output .= '<div clas="bwlb-content">';
          $output .= wpautop($content); // wrap the content with wp paragraphs
          $output .= '</div>';
        endif;

        // close out the form html
        $output .= '<p class="bwlb-input-container">
          <input type="submit" name="bwlb_submit" value="sign up" />
        </p>
      </form>
    </div>
  ';

  return $output;

}


/* 3. filters */

// 3.1
// filters the display of the subscriber headings in the admin custom post list view
// wp passes in an array of the columns
function bwlb_subscriber_column_headers ( $columns ) {

  // create custom column header data
  // new associative array to override the incoming param
  $columns = array (
    'cb'    => '<input type="checkbox" />',  // checkbox in the subscriber display
    'title' => __('Subscriber Name'), // __() to allow for translatable text strings
    'email' => __('Email Address')
  );

  return $columns;
}

// 3.2
// filters the display of the subscriber data in the admin custom post list view
// wp passes in the column name and the id of the post
function bwlb_subscriber_column_data ( $column, $post_id ) {

  // init return text
  $output = '';

  switch ( $column ) {

    case 'title':
      // get the custom name data
      $fname = get_field('bwlb_fname', $post_id);
      $lname = get_field('bwlb_lname', $post_id);
      $output .= $fname . ' ' . $lname;
      break;
    case 'email':
      // get the custom email data
      $email = get_field('bwlb_email', $post_id);
      $output .= $email;
      break;
  }

  echo $output; // display the retrieved data
}

// 3.2.1
// register special custom admin title columns
function bwlb_register_custom_admin_titles() {
  add_filter ('the_title', 'bwlb_custom_admin_titles', 99, 2);
}

// 3.2.2
// deal with custom admin title column data for post types without titles
// wp passes in the title and post id
function bwlb_custom_admin_titles( $title, $post_id ) {

  global $post; // pulls in the post variable from the global scope

  $output = $title;

  if ( isset($post->post_type) ):   // see if the post has a valid post type
    switch ( $post->post_type ) {
      case 'bwlb_subscriber':  // check that we're using the subscriber type
        $fname = get_field('bwlb_fname', $post_id);
        $lname = get_field('bwlb_lname', $post_id);
        $output = $fname . ' ' . $lname; // setup the title to be the full name
    }
  endif;

  return $output;

}

// 3.3
// filters the display of the list headings in the admin custom post list view
// wp passes in an array of the columns
function bwlb_list_column_headers ( $columns ) {

  // create custom column header data
  // new associative array to override the incoming param
  $columns = array (
    'cb'    => '<input type="checkbox" />',  // checkbox in the subscriber display
    'title' => __('List Name'), // __() to allow for translatable text strings
    'shortcode' => __('Shortcode')
  );

  return $columns;
}

// 3.4
// filters the display of the list data in the admin custom post list view
// wp passes in the column name and the id of the post
function bwlb_list_column_data ( $column, $post_id ) {

  // init return text
  $output = '';

  switch ( $column ) {

    case 'shortcode':
      $output .= '[bwlb_form id="' . $post_id . '"]';
      break;
  }

  echo $output; // display the retrieved data
}

/* 4. external scripts */

/* 5. actions */

// 5.1
// save subscription data to an existing or new subscriber
function bwlb_save_subscription() {

  // init result data to be the negative outcome
  $result = array (
    'status' => 0,
    'message' => 'Subscription was not saved.'
  );

  // error storage
  $errors = array ();

  // php try/catch statement
  /*
  try {
    // code
  } catch (Exception $e) {
    // do something with $e
  }
  */

  try {

    // get the list id from the form post
    $list_id = (int) $_POST['bwlb_list'];

    // prepare the subscriber data from the post
    // esc_attr - wp function to clean input data and ensure it is safe
    $subscriber_data = array (
      'fname'=> esc_attr( $_POST['bwlb_fname'] ),
      'lname'=> esc_attr( $_POST['bwlb_lname'] ),
      'email'=> esc_attr( $_POST['bwlb_email'] )
    );

    // attempt to create/save subscriber
    $subscriber_id = bwlb_save_subscriber( $subscriber_data );

    // if saved subscriber id will be non zero
    if ( $subscriber_id ):

      // if already subscribed - create and use a helper function
      if (bwlb_subscriber_has_subscription( $subscriber_data, $list_id )):

        // get the list from the form post
        $list = get_post( $list_id );  // wp builtin function to get a post

        // setup the error message
        $result ['message'] .= esc_attr( $subscriber_data['email'] . ' is already subscribef to ' . $list->post_title . '.');

      else:

        // save the subscription
        $subscription_saved = bwlb_add_subscription ( $subscriber_id, $list_id );

        // check success (non zero)
        if ( $subscription_saved ):
          $result['status'] = 1;
          $result['message'] = 'Subscription saved';
        endif;
      endif;
    endif;

  } catch ( Exception $e ) {

    // php error - add to error message
    $result['message'] = 'Caught exception: ' . $e->getMessage();
  }

  // return as json string to be used in js / ajax
  bwlb_return_json($result);
}

// 5.2
// creates a new subscriber or updates an existing one
function bwlb_save_subscriber ( $subscriber_data ) {

  // init subscriber
  $subscriber_id = 0;

  try {

    $subscriber_id = bwlb_get_subscriber_id( $subscriber_data['email'] );

    // if not already a subscriber, add to subscribers
    if ( !$subscriber_id ):

      $subscriber_id = wp_insert_post ( // default wp function to add posts to db
        array (
          'post_type' => 'bwlb_subscriber',
          'post_title' => $subscriber_data['fname'] . ' ' . $subscriber_data['lname'],
          'post_status' => 'publish'
        ),
        true
      );
    endif;

    // add or update the meta data with wp function update_field
    update_field(bwlb_get_acf_key('bwlb_fname'), $subscriber_data['fname'], $subscriber_id);
    update_field(bwlb_get_acf_key('bwlb_lname'), $subscriber_data['lname'], $subscriber_id);
    update_field(bwlb_get_acf_key('bwlb_email'), $subscriber_data['email'], $subscriber_id);

  } catch ( Exception $e ) {

    // php error

  }

  // cleanup wp post data
  wp_reset_query();

  return $subscriber_id;

}

// 5.3
// adds list to subscriber's subscriptions
function bwlb_add_subscription ( $subscriber_id, $list_id ) {

  // init
  $subscription_saved = false;

  // subscriber is not subscribed to the passed list
  if ( !bwlb_subscriber_has_subscription($subscriber_id, $list_id) ):

    // get the subs and append the new list id
    $subscriptions = bwlb_get_subscriptions( $subscriber_id );
    array_push( $subscriptions, $list_id ); // same as subscriptions[]=$list_id;

    // update the subs
    update_field( bwlb_get_acf_key('bwlb_subscriptions'), $subscriptions, $subscriber_id );

    $subscription_saved = true;

  endif;

  return $subscription_saved;
}


/* 6. helpers */

// 6.1
// check a subscriber's subscriptions to see if the passed list is already there
function bwlb_subscriber_has_subscription ( $subscriber_id, $list_id ) {

  // init as negative outcome
  $has_subscription = false;

  // use wp function to get the subscriber 'object' (the custom post type)
  $subscriber = get_post($subscriber_id);

  // check the subscriptions
  $subscriptions = bwlb_get_subscriptions($subscriber_id);

  if ( in_array($list_id, $subscriptions) ):
    // subscriber is already subscribed
    $has_subscription = true;
  endif;

  return $has_subscription;
}

// 6.2
// get a subscriber id from their email address
function bwlb_get_subscriber_id($email) {

  // init
  $subscriber_id = 0;

  try {

    // check subscriber existence
    $subscriber_query = new WP_Query(
      array(
        'post_type'=> 'bwlb_subscriber',
        'posts_per_page' => 1,
        'meta_key' => 'bwlb_email',
        'meta_query' => array (
          array (
            'key' => 'bwlb_email',
            'value' => $email,
            'compare' => '='
          )
        )
      )
    );

    if ($subscriber_query->have_posts()):

      $subscriber_query->the_post();
      $suscriber_id = get_the_ID();  // from the_post
    endif;

  } catch (Exception $e) {
    // error
  }

  // reset wp post object - clear the_post object
  wp_reset_query();

  return (int) $subscriber_id;

}

// 6.3
// get an array of list_ids
function bwlb_get_subscriptions ( $subscriber_id ) {

  // init
  $subscriptions = array();

  $lists = get_field( bwlb_get_acf_key('bwlb_subscriptions'), $subscriber_id );

  if ( $lists ):

    // check array-ness and 1 or more items
    if ( is_array($lists) && count($lists) ):

      // build up subscriptions as an array of lists
      foreach ($lists as &$list):
        $subscriptions[]= (int) $list->ID;
      endforeach;

    elseif ( is_numeric($lists) ):
      $subscriptions[]=$lists;
    endif;

  endif;

  return (array)$subscriptions;
}

// 6.4
// convert php array into json
function bwlb_return_json ( $php_array ) {

  // builtin php function to do the encoding
  $json_result = json_encode( $php_array);

  // return and kill the php process
  die($json_result);

  // stop all other php processing
  exit;

}

// 6.5
// switches out custom field names for the ACT field key names
function bwlb_get_acf_key( $field_name ) {

  $field_key = $field_name;

  switch ( $field_name ) {

    case 'bwlb_fname':
      $field_key = 'field_57bf831d4e1d0';
      break;
    case 'bwlb_lname':
      $field_key = 'field_57bf83344e1d1';
      break;
    case 'bwlb_email':
      $field_key = 'field_57bf83504e1d2';
      break;
    case 'bwlb_subscriptions':
      $field_key = 'field_57bf83674e1d3';
      break;

  }

  return $field_key;

}

// 6.6
// return an array of subscriber data, including the subscriptions
function bwlb_get_subscriber_data ( $subscriber_id) {
  // init
  $subscriber_data = array();

  // get the subscriber object (custom post type)
  $subscriber = get_post($subscriber_id);

    // validate and build array
    if ( bwlb_validate_subscriber($subscriber)):

      $fname = get_field(bwlb_get_acf_key('bwlb_fname'), $subscriber_id);
      $lname = get_field(bwlb_get_acf_key('bwlb_lname'), $subscriber_id);

      $subscriber_data = array (
        'name' => $fname . ' ' . $lname,
        'fname' => $fname,
        'lname' => $lname,
        'email' => get_field(bwlb_get_acf_key('bwlb_email'), $subscriber_id),
        'subscriptions' => bwlb_get_subscriptions($subscriber_id)
      );

    endif;

  return $subscriber_data;
}

// 6.7
// ensure subscriber has a post type and it's the correct one
function bwlb_validate_subscriber($subscriber) {

  $valid_subscriber = false;

  if ( isset($subscriber->post_type) && $subscriber->post_type == 'bwlb_subscriber'):
    $valid_subscriber = true;
  endif;

  return $valid_subscriber;

}

/* 7. custom post types	*/

/* 8. admin pages */

/* 9. settings */





// eof
?>
