<?php

// generated by CPTUI (custom post types)

add_action( 'init', 'bwlb_register_bwlb_list' );
function bwlb_register_bwlb_list() {

	$labels = array(
		"name" => __( 'Lists', 'twentysixteen' ),
		"singular_name" => __( 'List', 'twentysixteen' ),
		);

	$args = array(
		"label" => __( 'Lists', 'twentysixteen' ),
		"labels" => $labels,
		"description" => "",
		"public" => true,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => false,
		"rest_base" => "",
		"has_archive" => false,
		"show_in_menu" => false,
				"exclude_from_search" => true,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "bwlb_list", "with_front" => true ),
		"query_var" => true,

		"supports" => array( "title" ),					);
	register_post_type( "bwlb_list", $args );

// End of cptui_register_my_cpts()
}


?>
