<?php

// generated by CPTUI (custom post types ui)
add_action( 'init', 'bwlb_register_bwlb_subscriber' );
function bwlb_register_bwlb_subscriber() {
	$labels = array(
		"name" => __( 'Subscribers', 'twentysixteen' ),
		"singular_name" => __( 'Subscriber', 'twentysixteen' ),
		);

	$args = array(
		"label" => __( 'Subscribers', 'twentysixteen' ),
		"labels" => $labels,
		"description" => "",
		"public" => false,
		"publicly_queryable" => true,
		"show_ui" => true,
		"show_in_rest" => false,
		"rest_base" => "",
		"has_archive" => false,
		"show_in_menu" => false,
				"exclude_from_search" => true,
		"capability_type" => "post",
		"map_meta_cap" => true,
		"hierarchical" => false,
		"rewrite" => array( "slug" => "bwlb_subscriber", "with_front" => false ),
		"query_var" => true,
							);
	register_post_type( "bwlb_subscriber", $args );



// End of cptui_register_my_cpts()
}



// generated by advanced-custom-fields

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_subscriber-details',
		'title' => 'Subscriber Details',
		'fields' => array (
			array (
				'key' => 'field_57bf831d4e1d0',
				'label' => 'First Name',
				'name' => 'bwlb_fname',
				'type' => 'text',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57bf83344e1d1',
				'label' => 'Last Name',
				'name' => 'bwlb_lname',
				'type' => 'text',
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_57bf83504e1d2',
				'label' => 'Email',
				'name' => 'bwlb_email',
				'type' => 'email',
				'required' => 1,
				'default_value' => '',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
			),
			array (
				'key' => 'field_57bf83674e1d3',
				'label' => 'Subscriptions',
				'name' => 'bwlb_subscriptions',
				'type' => 'post_object',
				'post_type' => array (
					0 => 'bwlb_list',
				),
				'taxonomy' => array (
					0 => 'all',
				),
				'allow_null' => 1,
				'multiple' => 1,
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'bwlb_subscriber',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'acf_after_title',
			'layout' => 'default',
			'hide_on_screen' => array (
				0 => 'permalink',
				1 => 'the_content',
				2 => 'excerpt',
				3 => 'custom_fields',
				4 => 'discussion',
				5 => 'comments',
				6 => 'revisions',
				7 => 'slug',
				8 => 'author',
				9 => 'format',
				10 => 'featured_image',
				11 => 'categories',
				12 => 'tags',
				13 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}

?>
